
platform :osx, '10.15'

target 'CLILoggerServer' do
    pod 'CocoaLumberjack/Swift', :modular_headers => true
    pod 'CocoaAsyncSocket', :modular_headers => true
    pod 'CLILogger', :path => '../'
    pod 'RainbowSwift', '~> 4.0.0'
end
