# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#



default_platform(:mac)

platform :mac do
  desc "Build a release executable file."
  lane :build do
    cocoapods(
      # clean_install: true,
      podfile: "./Podfile"
    )

    build_app(
      workspace: "CLILoggerServer.xcworkspace",
      configuration: "Release",
      scheme: "CLILoggerServer",
      silent: true,
      clean: true,
      output_directory: "./build/Release",
      output_name: "cli-logger",
    )

    notification(subtitle: "Finished Building", message: "Ready to upload...")
  end

  desc "Upload the existing release build to github release page."
  lane :upload do
    changelog = prompt(
      text: "Changelog: \n",
      multi_line_end_keyword: "EOF"
    )
    commit = last_git_commit
    tag_name = sh("cat ../../.version").strip
    description = "#{changelog}\n\nCommit: #{commit[:commit_hash]}\n"

    github_release = set_github_release(
      repository_name: "CLILogger/CLILogger",
      api_token: ENV["GITHUB_TOKEN"],
      name: "CLILoggerServer(cli-logger)",
      tag_name: tag_name,
      description: description,
      commitish: "master",
      upload_assets: ["./build/Release/cli-logger"]
    )

    notification(subtitle: "Finished Uploading", message: "", open: "https://github.com/CLILogger/CLILogger/releases")
  end

  desc "Build the release archive and upload it to github release page."
  lane :fire do
    build
    upload
  end
end
